version: '3'

services:
  app:
    build: .
    ports:
      - "9091:9091"
    environment:
      - NODE_ENV=production
      - PORT=9091
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_COOKIE_EXPIRE=${JWT_COOKIE_EXPIRE}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: always
    depends_on:
      - mongo
    networks:
      - mealwise-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mealwise-network
    restart: always

networks:
  mealwise-network:
    driver: bridge

volumes:
  mongo-data: